---
- name: Setup Ansible to each node
  hosts: all
  connection: local
  become: no
  become_user: vagrant
  serial: 1
  gather_facts: no
  vars:
    ansible_password: vagrant
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - debug: var=ansible_host

    - name: restart ssh service
      service:
        name: ssh
        state: restarted
      run_once: true

    - name: copy public key to each node
      become: true
      command: sshpass -p {{ ansible_password }} ssh-copy-id -i ~/.ssh/id_rsa.pub vagrant@{{ item }} -f -o StrictHostKeyChecking=no
      with_items:
        - "{{ ansible_host }}"
      run_once: true
    
